[build]
  base    = "."
  command = "npm install && npm run build -w packages/shared && npm run build -w apps/web"
  publish = "apps/web/.next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://yaxis-assessment.onrender.com/api"

[functions]
  directory = "apps/web/.netlify/functions-internal"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  [plugins.inputs]
    appDir = "apps/web"
